In [1]:
#machine learning and its types

supervised learning
  *regression
  *random forest
  *decision tree
  *naive bayes
  *linear
  *svm
2)unsupervised learning
  * KNN
  *clustering
  *dbscan

SyntaxError: unmatched ')' (3487808658.py, line 10)

In [7]:
#linear regression
import pandas as pd
sd={'x':[3,4,5,6,1,8],'y':[12,11,29,4,5,7]}
print(sd)
data=pd.DataFrame(sd)
data
print(data.shape)

{'x': [3, 4, 5, 6, 1, 8], 'y': [12, 11, 29, 4, 5, 7]}
(6, 2)


In [5]:
x=data.iloc[:,:-1].values
x

array([[3],
       [4],
       [5],
       [6],
       [1],
       [8]], dtype=int64)

In [7]:
y=data.iloc[:,1].values
y

array([12, 11, 29,  4,  5,  7], dtype=int64)

In [9]:
!pip install scikit-learn

In [10]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x,y)

LinearRegression()

In [11]:
print(dir(regressor))
print(regressor.coef_)
print(regressor.intercept_)

['__abstractmethods__', '__annotations__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__sklearn_clone__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_build_request_for_signature', '_check_feature_names', '_check_n_features', '_decision_function', '_doc_link_module', '_doc_link_template', '_doc_link_url_param_generator', '_estimator_type', '_get_default_requests', '_get_doc_link', '_get_metadata_request', '_get_param_names', '_get_tags', '_more_tags', '_parameter_constraints', '_repr_html_', '_repr_html_inner', '_repr_mimebundle_', '_set_intercept', '_validate_data', '_validate_params', 'coef_', 'copy_X', 'fit', 'fit_intercept', 'get_metadata_routing', 'get_params', 'intercept_', 'n_feat

In [12]:
import numpy as np
o={'xpredict':[2,4,6,8,2,12]}
a=pd.DataFrame(o)
print(a)
print(type(a))
areshape=a['xpredict'].values.reshape(-1,1)
areshape

   xpredict
0         2
1         4
2         6
3         8
4         2
5        12
<class 'pandas.core.frame.DataFrame'>


array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [ 2],
       [12]], dtype=int64)

In [13]:
regressor.predict(areshape)

array([10.99435028, 11.26553672, 11.53672316, 11.8079096 , 10.99435028,
       12.35028249])

In [9]:
import pandas as pd
sd={'x':[3,4,5,6,1,8],'x1':[45,15,54,22,65,32],'y':[12,11,29,4,5,7]}
print(sd)
data=pd.DataFrame(sd)
data
print(data.shape)

{'x': [3, 4, 5, 6, 1, 8], 'x1': [45, 15, 54, 22, 65, 32], 'y': [12, 11, 29, 4, 5, 7]}
(6, 3)


In [15]:
x=data.iloc[:,:-1].values
x

array([[ 3, 45],
       [ 4, 15],
       [ 5, 54],
       [ 6, 22],
       [ 1, 65],
       [ 8, 32]], dtype=int64)

In [16]:
y=data.iloc[:,1].values
y

array([45, 15, 54, 22, 65, 32], dtype=int64)

In [17]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x,y)

LinearRegression()

In [18]:
print(dir(regressor))
print(regressor.coef_)
print(regressor.intercept_)

['__abstractmethods__', '__annotations__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__setstate__', '__sizeof__', '__sklearn_clone__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_build_request_for_signature', '_check_feature_names', '_check_n_features', '_decision_function', '_doc_link_module', '_doc_link_template', '_doc_link_url_param_generator', '_estimator_type', '_get_default_requests', '_get_doc_link', '_get_metadata_request', '_get_param_names', '_get_tags', '_more_tags', '_parameter_constraints', '_repr_html_', '_repr_html_inner', '_repr_mimebundle_', '_set_intercept', '_validate_data', '_validate_params', 'coef_', 'copy_X', 'fit', 'fit_intercept', 'get_metadata_routing', 'get_params', 'intercept_', 'n_feat

In [19]:
ypredict=np.array([[3,45],[4,15]])
regressor.predict(ypredict)

array([45., 15.])

In [11]:
file_path = r'‪C:\Users\keert\Downloads\\Salary_Data.csv'.replace('\u202a','')
SampleDataFrame=pd.read_csv(file_path)
SampleDataFrame

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [13]:
x=SampleDataFrame.iloc[:,:-1].values
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [15]:
y=SampleDataFrame.iloc[:,-1].values
y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [17]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x,y)

LinearRegression()

In [19]:
print(reg.coef_)
print(reg.intercept_)

[9449.96232146]
25792.20019866871


In [23]:
import numpy as np
ypred=np.array([[3.9]])
reg.predict(ypred)


array([62647.05325234])

In [27]:
import pickle
pickle.dump(reg,open('websitelinear.pkl','wb'))
