In [5]:
# Machine learning and its types
# 1. supervised learning 
# * regression - single linear 
# *random forest 
# *decision tree
# *native bayes
# *linear
# *SVM


# 2)unsupervised learning
# *KNN
# *clustering
# * DBscan



In [1]:
#linear regression
import pandas as pd
df={'x':[23,45,23,4,45,67,7],'y':[54,89,2,4,7,9,7]}
data=pd.DataFrame(df)
print(data)


    x   y
0  23  54
1  45  89
2  23   2
3   4   4
4  45   7
5  67   9
6   7   7


In [2]:
x=data.iloc[:,:-1].values
x

array([[23],
       [45],
       [23],
       [ 4],
       [45],
       [67],
       [ 7]], dtype=int64)

In [3]:
y=data.iloc[:,1].values
y

array([54, 89,  2,  4,  7,  9,  7], dtype=int64)

In [7]:
!pip install scikit-learn

In [8]:
from sklearn.linear_model import LinearRegression
regressor1=LinearRegression()
regressor1.fit(x,y)

LinearRegression()

In [9]:
print(dir(regressor))

NameError: name 'regressor' is not defined

In [ ]:
print(regressor.coef_)

In [ ]:
print(regressor.intercept_)

In [ ]:
#above is model and we created a x and prediteding y
import numpy as np
o={'xpredict':[23,6,4,6,8,9,10]}
a=pd.DataFrame(o)
print(a)
areshape=a['xpredict'].values.reshape(-1,1)
areshape

In [ ]:
#y value for above x
regressor1.predict(areshape)

In [ ]:
# inp=[10,6,4,6,8,9,10]
# xvalues=[int(x) for x in inp]
# final_x=[np.array(xvalues)]
# print(final_x)

In [ ]:
import pandas as pd
df={'x':[23,19,21,15,18],'x1':[22,21,23,18,20],'y':[10,12,8,12,17]}
data=pd.DataFrame(df)
print(data)

In [ ]:
x=data.iloc[:,:-1].values
x

In [20]:
y=data.iloc[:,1].values
y

array([54, 89,  2,  4,  7,  9,  7], dtype=int64)

In [22]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x,y)

LinearRegression()

In [24]:
print(regressor.coef_)
print(regressor.intercept_)

[0.32622035]
14.598406447476876


In [26]:
ypredict=np.array([[23,22],[56,7]])

In [46]:
regressor.predict(ypredict)

array([16.2295082])

In [48]:
import pickle
pickle.dump(regressor1,open('singlelinear.pk1','wb'))

In [50]:
import pickle 
model=pickle.load(open('singlelinear.pk1','rb'))

In [52]:
print(model.intercept_,model.coef_)

14.598406447476876 [0.32622035]


In [54]:
xy=float(input('number')) 
print(xy)

number 3


3.0


In [56]:
import numpy as np
xvalue=[]
xvalue.append(xy)
ypredict=[np.array((xvalue))]
model.predict(ypredict)

array([15.5770675])

In [58]:
import numpy as np
y=[]
for a in range(5):
    x=[]
    num=float(input('number')) 
    x.append(num)
    ypredict=[np.array(x)]
    print(model.predict(ypredict))

number 2


[15.25084715]


number 4


[15.90328785]


number 5


[16.2295082]


number 67


[36.45516989]


number 8


[17.20816925]


In [62]:
final=[]
for a in range(5):
    x=[]
    num=float(input('number')) 
    x.append(num)
    final.append(x)
    ypredict=[np.array(x)]
ypredict=np.array(final)
print(ypredict)
print(model.predict(ypredict))
    

number 3
number 4
number 6
number 676
number 7


[[  3.]
 [  4.]
 [  6.]
 [676.]
 [  7.]]
[ 15.5770675   15.90328785  16.55572855 235.12336295  16.8819489 ]


In [64]:
from tkinter import *
root=Tk()
root.title('ypredict')
root.geometry('400x300')
def predictvalue():
    x=[]
    num=float(v.get())
    x.append(num)
    ypredict=[np.array(x)]
    o.set(model.predict(ypredict))
Label(root,text='enter a number').grid(row=0,column=0)
v=StringVar()
Entry(root,textvariable=v).grid(row=0,column=1)
Button(root,text='submit',command=predictvalue).grid(row=1,column=1)
Label(root,text='predict').grid(row=2,column=0)
o=StringVar()
Entry(root,textvariable=o).grid(row=2,column=1)
root.mainloop()