In [3]:
import pandas as pd
#import matplotlib.pyplot as plt
#from sklearn.tree import DecisionTreeClassifier, plot_tree, export_text
from sklearn.model_selection import train_test_split
#from sklearn import tree
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression

# Data
data = {
    'Day': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
    'Outlook': ['Sunny', 'Sunny', 'Overcast', 'Rain', 'Rain', 'Rain', 'Overcast', 'Sunny', 'Sunny', 'Rain', 'Sunny', 'Overcast', 'Overcast', 'Rain'],
    'Temperature': ['Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Cool', 'Cool', 'Mild', 'Cool', 'Mild', 'Mild', 'Mild', 'Hot', 'Mild'],
    'Humidity': ['High', 'High', 'High', 'High', 'Normal', 'Normal', 'Normal', 'High', 'Normal', 'Normal', 'Normal', 'High', 'Normal', 'High'],
    'Wind': ['Weak', 'Strong', 'Weak', 'Weak', 'Weak', 'Strong', 'Strong', 'Weak', 'Weak', 'Weak', 'Strong', 'Strong', 'Weak', 'Strong'],
    'Play cricket': ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No']
}

# Create DataFrame
df = pd.DataFrame(data)
print(df)

# Preprocess the data
# Convert categorical variables to numerical values
df['Outlook'] = df['Outlook'].map({'Sunny': 0, 'Overcast': 1, 'Rain': 2})
df['Temperature'] = df['Temperature'].map({'Hot': 0, 'Mild': 1, 'Cool': 2})
df['Humidity'] = df['Humidity'].map({'High': 0, 'Normal': 1})
df['Wind'] = df['Wind'].map({'Weak': 0, 'Strong': 1})
df['Play cricket'] = df['Play cricket'].map({'No': 0, 'Yes': 1})

# Split the data into features and target variable
X = df.drop(columns=['Day', 'Play cricket'])
y = df['Play cricket']
print(X)
print(y)
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


    Day   Outlook Temperature Humidity    Wind Play cricket
0     1     Sunny         Hot     High    Weak           No
1     2     Sunny         Hot     High  Strong           No
2     3  Overcast         Hot     High    Weak          Yes
3     4      Rain        Mild     High    Weak          Yes
4     5      Rain        Cool   Normal    Weak          Yes
5     6      Rain        Cool   Normal  Strong           No
6     7  Overcast        Cool   Normal  Strong          Yes
7     8     Sunny        Mild     High    Weak           No
8     9     Sunny        Cool   Normal    Weak          Yes
9    10      Rain        Mild   Normal    Weak          Yes
10   11     Sunny        Mild   Normal  Strong          Yes
11   12  Overcast        Mild     High  Strong          Yes
12   13  Overcast         Hot   Normal    Weak          Yes
13   14      Rain        Mild     High  Strong           No
    Outlook  Temperature  Humidity  Wind
0         0            0         0     0
1         0       

In [5]:
model = LogisticRegression()
model.fit(X, y)

LogisticRegression()

In [9]:
y_pred = model.predict(X)
print(y_pred)

print("----------------")
# Print evaluation metrics
print("Accuracy:", accuracy_score(y, y_pred))
print("\nClassification Report:\n", classification_report(y, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y, y_pred))

[1 0 1 1 1 1 1 1 1 1 1 0 1 1]
----------------
Accuracy: 0.6428571428571429

Classification Report:
               precision    recall  f1-score   support

           0       0.50      0.20      0.29         5
           1       0.67      0.89      0.76         9

    accuracy                           0.64        14
   macro avg       0.58      0.54      0.52        14
weighted avg       0.61      0.64      0.59        14


Confusion Matrix:
 [[1 4]
 [1 8]]


In [11]:
import numpy as np
a=np.array([[0, 0, 0, 0]])
a
y_pred = model.predict(a)
print(y_pred)

[1]


C:\Users\keert\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [13]:
probabilities = model.predict_proba(a)
prediction = model.predict(a)
print(prediction)
print(f"Probabilities: {probabilities}")

[1]
Probabilities: [[0.48085221 0.51914779]]


C:\Users\keert\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\keert\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [15]:
print(model.coef_)
print(model.intercept_)

[[ 0.23248199  0.16836414  0.75894008 -0.51472909]]
[0.07662865]
